package jp.co.foo.common.dao;

import java.util.List;
import javax.inject.Named;

import jp.co.foo.common.dto.*;

import org.apache.ibatis.annotations.Param;


@Named("mastersIndustryDataMapper")
public interface IndustryDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int countByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int deleteByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int insert(IndustryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int insertSelective(IndustryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    List<IndustryDto> selectByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    IndustryDto selectByPrimaryKey(@Param("id")Integer id, @Param("forUpdate")boolean forUpdate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int updateByExampleSelective(@Param("record") IndustryDto record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int updateByExample(@Param("record") IndustryDto record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int updateByPrimaryKeySelective(IndustryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    int updateByPrimaryKey(IndustryDto record);
    
    int lock();
}