package jp.co.foo.datamapper;

import java.util.List;
import jp.co.foo.dto.EmpDto;
import jp.co.foo.dto.EmpExample;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int deleteByPrimaryKey(Short empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int insert(EmpDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int insertSelective(EmpDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    List<EmpDto> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    EmpDto selectByPrimaryKey(Short empno, boolean forUpdate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int updateByExampleSelective(@Param("record") EmpDto record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int updateByExample(@Param("record") EmpDto record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int updateByPrimaryKeySelective(EmpDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    int updateByPrimaryKey(EmpDto record);
}