package jp.co.foo.datamapper;

import java.util.List;
import jp.co.foo.dto.Zip2Dto;
import jp.co.foo.dto.Zip2Example;
import org.apache.ibatis.annotations.Param;

public interface Zip2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    int countByExample(Zip2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    int deleteByExample(Zip2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    int insert(Zip2Dto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    int insertSelective(Zip2Dto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    List<Zip2Dto> selectByExample(Zip2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    int updateByExampleSelective(@Param("record") Zip2Dto record, @Param("example") Zip2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    int updateByExample(@Param("record") Zip2Dto record, @Param("example") Zip2Example example);
}