package jp.co.foo.common.dto;


public class IndustryDto extends AbstractDto<Integer> {
		
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.CODE
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.NAME
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.FINANCE_FLG
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    private Boolean financeFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.DELETE_FLG
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INDUSTRY
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    private static final long serialVersionUID = 1375001614385L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.CODE
     *
     * @return the value of INDUSTRY.CODE
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.CODE
     *
     * @param code the value for INDUSTRY.CODE
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.NAME
     *
     * @return the value of INDUSTRY.NAME
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.NAME
     *
     * @param name the value for INDUSTRY.NAME
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.FINANCE_FLG
     *
     * @return the value of INDUSTRY.FINANCE_FLG
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public Boolean getFinanceFlg() {
        return financeFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.FINANCE_FLG
     *
     * @param financeFlg the value for INDUSTRY.FINANCE_FLG
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public void setFinanceFlg(Boolean financeFlg) {
        this.financeFlg = financeFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.DELETE_FLG
     *
     * @return the value of INDUSTRY.DELETE_FLG
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.DELETE_FLG
     *
     * @param deleteFlg the value for INDUSTRY.DELETE_FLG
     *
     * @mbggenerated Sun Jul 28 17:53:34 JST 2013
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }
}