package jp.co.foo.dto;

import java.util.List;


public class DeptDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DEPTNO
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    private Short deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.DNAME
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPT.LOC
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    private String loc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEPT
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    private static final long serialVersionUID = 1406033798388L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DEPTNO
     *
     * @return the value of DEPT.DEPTNO
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    public Short getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DEPTNO
     *
     * @param deptno the value for DEPT.DEPTNO
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    public void setDeptno(Short deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.DNAME
     *
     * @return the value of DEPT.DNAME
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.DNAME
     *
     * @param dname the value for DEPT.DNAME
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPT.LOC
     *
     * @return the value of DEPT.LOC
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPT.LOC
     *
     * @param loc the value for DEPT.LOC
     *
     * @mbggenerated Tue Jul 22 21:56:38 JST 2014
     */
    public void setLoc(String loc) {
        this.loc = loc;
    }
    
    private List<EmpDto> emps;

	/**
	 * @return the emps
	 */
	public List<EmpDto> getEmps() {
		return emps;
	}

	/**
	 * @param emps the emps to set
	 */
	public void setEmps(List<EmpDto> emps) {
		this.emps = emps;
	}
    
    
}