package jp.co.foo.dto;

import java.util.ArrayList;
import java.util.List;

public class Zip2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public Zip2Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJisCodeIsNull() {
            addCriterion("JIS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andJisCodeIsNotNull() {
            addCriterion("JIS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andJisCodeEqualTo(String value) {
            addCriterion("JIS_CODE =", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeNotEqualTo(String value) {
            addCriterion("JIS_CODE <>", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeGreaterThan(String value) {
            addCriterion("JIS_CODE >", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeGreaterThanOrEqualTo(String value) {
            addCriterion("JIS_CODE >=", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeLessThan(String value) {
            addCriterion("JIS_CODE <", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeLessThanOrEqualTo(String value) {
            addCriterion("JIS_CODE <=", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeLike(String value) {
            addCriterion("JIS_CODE like", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeNotLike(String value) {
            addCriterion("JIS_CODE not like", value, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeIn(List<String> values) {
            addCriterion("JIS_CODE in", values, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeNotIn(List<String> values) {
            addCriterion("JIS_CODE not in", values, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeBetween(String value1, String value2) {
            addCriterion("JIS_CODE between", value1, value2, "jisCode");
            return (Criteria) this;
        }

        public Criteria andJisCodeNotBetween(String value1, String value2) {
            addCriterion("JIS_CODE not between", value1, value2, "jisCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldIsNull() {
            addCriterion("POSTAL_CODE_OLD is null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldIsNotNull() {
            addCriterion("POSTAL_CODE_OLD is not null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldEqualTo(String value) {
            addCriterion("POSTAL_CODE_OLD =", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldNotEqualTo(String value) {
            addCriterion("POSTAL_CODE_OLD <>", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldGreaterThan(String value) {
            addCriterion("POSTAL_CODE_OLD >", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldGreaterThanOrEqualTo(String value) {
            addCriterion("POSTAL_CODE_OLD >=", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldLessThan(String value) {
            addCriterion("POSTAL_CODE_OLD <", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldLessThanOrEqualTo(String value) {
            addCriterion("POSTAL_CODE_OLD <=", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldLike(String value) {
            addCriterion("POSTAL_CODE_OLD like", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldNotLike(String value) {
            addCriterion("POSTAL_CODE_OLD not like", value, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldIn(List<String> values) {
            addCriterion("POSTAL_CODE_OLD in", values, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldNotIn(List<String> values) {
            addCriterion("POSTAL_CODE_OLD not in", values, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldBetween(String value1, String value2) {
            addCriterion("POSTAL_CODE_OLD between", value1, value2, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeOldNotBetween(String value1, String value2) {
            addCriterion("POSTAL_CODE_OLD not between", value1, value2, "postalCodeOld");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIsNull() {
            addCriterion("POSTAL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIsNotNull() {
            addCriterion("POSTAL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeEqualTo(String value) {
            addCriterion("POSTAL_CODE =", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotEqualTo(String value) {
            addCriterion("POSTAL_CODE <>", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeGreaterThan(String value) {
            addCriterion("POSTAL_CODE >", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("POSTAL_CODE >=", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLessThan(String value) {
            addCriterion("POSTAL_CODE <", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLessThanOrEqualTo(String value) {
            addCriterion("POSTAL_CODE <=", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLike(String value) {
            addCriterion("POSTAL_CODE like", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotLike(String value) {
            addCriterion("POSTAL_CODE not like", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIn(List<String> values) {
            addCriterion("POSTAL_CODE in", values, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotIn(List<String> values) {
            addCriterion("POSTAL_CODE not in", values, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeBetween(String value1, String value2) {
            addCriterion("POSTAL_CODE between", value1, value2, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotBetween(String value1, String value2) {
            addCriterion("POSTAL_CODE not between", value1, value2, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaIsNull() {
            addCriterion("PREFECTURE_KANA is null");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaIsNotNull() {
            addCriterion("PREFECTURE_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaEqualTo(String value) {
            addCriterion("PREFECTURE_KANA =", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaNotEqualTo(String value) {
            addCriterion("PREFECTURE_KANA <>", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaGreaterThan(String value) {
            addCriterion("PREFECTURE_KANA >", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaGreaterThanOrEqualTo(String value) {
            addCriterion("PREFECTURE_KANA >=", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaLessThan(String value) {
            addCriterion("PREFECTURE_KANA <", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaLessThanOrEqualTo(String value) {
            addCriterion("PREFECTURE_KANA <=", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaLike(String value) {
            addCriterion("PREFECTURE_KANA like", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaNotLike(String value) {
            addCriterion("PREFECTURE_KANA not like", value, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaIn(List<String> values) {
            addCriterion("PREFECTURE_KANA in", values, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaNotIn(List<String> values) {
            addCriterion("PREFECTURE_KANA not in", values, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaBetween(String value1, String value2) {
            addCriterion("PREFECTURE_KANA between", value1, value2, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanaNotBetween(String value1, String value2) {
            addCriterion("PREFECTURE_KANA not between", value1, value2, "prefectureKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaIsNull() {
            addCriterion("CITY_KANA is null");
            return (Criteria) this;
        }

        public Criteria andCityKanaIsNotNull() {
            addCriterion("CITY_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andCityKanaEqualTo(String value) {
            addCriterion("CITY_KANA =", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotEqualTo(String value) {
            addCriterion("CITY_KANA <>", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaGreaterThan(String value) {
            addCriterion("CITY_KANA >", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_KANA >=", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLessThan(String value) {
            addCriterion("CITY_KANA <", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLessThanOrEqualTo(String value) {
            addCriterion("CITY_KANA <=", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLike(String value) {
            addCriterion("CITY_KANA like", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotLike(String value) {
            addCriterion("CITY_KANA not like", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaIn(List<String> values) {
            addCriterion("CITY_KANA in", values, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotIn(List<String> values) {
            addCriterion("CITY_KANA not in", values, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaBetween(String value1, String value2) {
            addCriterion("CITY_KANA between", value1, value2, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotBetween(String value1, String value2) {
            addCriterion("CITY_KANA not between", value1, value2, "cityKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaIsNull() {
            addCriterion("TOWN_KANA is null");
            return (Criteria) this;
        }

        public Criteria andTownKanaIsNotNull() {
            addCriterion("TOWN_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andTownKanaEqualTo(String value) {
            addCriterion("TOWN_KANA =", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotEqualTo(String value) {
            addCriterion("TOWN_KANA <>", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaGreaterThan(String value) {
            addCriterion("TOWN_KANA >", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaGreaterThanOrEqualTo(String value) {
            addCriterion("TOWN_KANA >=", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaLessThan(String value) {
            addCriterion("TOWN_KANA <", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaLessThanOrEqualTo(String value) {
            addCriterion("TOWN_KANA <=", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaLike(String value) {
            addCriterion("TOWN_KANA like", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotLike(String value) {
            addCriterion("TOWN_KANA not like", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaIn(List<String> values) {
            addCriterion("TOWN_KANA in", values, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotIn(List<String> values) {
            addCriterion("TOWN_KANA not in", values, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaBetween(String value1, String value2) {
            addCriterion("TOWN_KANA between", value1, value2, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotBetween(String value1, String value2) {
            addCriterion("TOWN_KANA not between", value1, value2, "townKana");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiIsNull() {
            addCriterion("PREFECTURE_KANJI is null");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiIsNotNull() {
            addCriterion("PREFECTURE_KANJI is not null");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiEqualTo(String value) {
            addCriterion("PREFECTURE_KANJI =", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiNotEqualTo(String value) {
            addCriterion("PREFECTURE_KANJI <>", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiGreaterThan(String value) {
            addCriterion("PREFECTURE_KANJI >", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiGreaterThanOrEqualTo(String value) {
            addCriterion("PREFECTURE_KANJI >=", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiLessThan(String value) {
            addCriterion("PREFECTURE_KANJI <", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiLessThanOrEqualTo(String value) {
            addCriterion("PREFECTURE_KANJI <=", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiLike(String value) {
            addCriterion("PREFECTURE_KANJI like", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiNotLike(String value) {
            addCriterion("PREFECTURE_KANJI not like", value, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiIn(List<String> values) {
            addCriterion("PREFECTURE_KANJI in", values, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiNotIn(List<String> values) {
            addCriterion("PREFECTURE_KANJI not in", values, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiBetween(String value1, String value2) {
            addCriterion("PREFECTURE_KANJI between", value1, value2, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andPrefectureKanjiNotBetween(String value1, String value2) {
            addCriterion("PREFECTURE_KANJI not between", value1, value2, "prefectureKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiIsNull() {
            addCriterion("CITY_KANJI is null");
            return (Criteria) this;
        }

        public Criteria andCityKanjiIsNotNull() {
            addCriterion("CITY_KANJI is not null");
            return (Criteria) this;
        }

        public Criteria andCityKanjiEqualTo(String value) {
            addCriterion("CITY_KANJI =", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiNotEqualTo(String value) {
            addCriterion("CITY_KANJI <>", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiGreaterThan(String value) {
            addCriterion("CITY_KANJI >", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_KANJI >=", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiLessThan(String value) {
            addCriterion("CITY_KANJI <", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiLessThanOrEqualTo(String value) {
            addCriterion("CITY_KANJI <=", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiLike(String value) {
            addCriterion("CITY_KANJI like", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiNotLike(String value) {
            addCriterion("CITY_KANJI not like", value, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiIn(List<String> values) {
            addCriterion("CITY_KANJI in", values, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiNotIn(List<String> values) {
            addCriterion("CITY_KANJI not in", values, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiBetween(String value1, String value2) {
            addCriterion("CITY_KANJI between", value1, value2, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andCityKanjiNotBetween(String value1, String value2) {
            addCriterion("CITY_KANJI not between", value1, value2, "cityKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiIsNull() {
            addCriterion("TOWN_KANJI is null");
            return (Criteria) this;
        }

        public Criteria andTownKanjiIsNotNull() {
            addCriterion("TOWN_KANJI is not null");
            return (Criteria) this;
        }

        public Criteria andTownKanjiEqualTo(String value) {
            addCriterion("TOWN_KANJI =", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiNotEqualTo(String value) {
            addCriterion("TOWN_KANJI <>", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiGreaterThan(String value) {
            addCriterion("TOWN_KANJI >", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiGreaterThanOrEqualTo(String value) {
            addCriterion("TOWN_KANJI >=", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiLessThan(String value) {
            addCriterion("TOWN_KANJI <", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiLessThanOrEqualTo(String value) {
            addCriterion("TOWN_KANJI <=", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiLike(String value) {
            addCriterion("TOWN_KANJI like", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiNotLike(String value) {
            addCriterion("TOWN_KANJI not like", value, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiIn(List<String> values) {
            addCriterion("TOWN_KANJI in", values, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiNotIn(List<String> values) {
            addCriterion("TOWN_KANJI not in", values, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiBetween(String value1, String value2) {
            addCriterion("TOWN_KANJI between", value1, value2, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownKanjiNotBetween(String value1, String value2) {
            addCriterion("TOWN_KANJI not between", value1, value2, "townKanji");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagIsNull() {
            addCriterion("TOWN_DIVIDE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagIsNotNull() {
            addCriterion("TOWN_DIVIDE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagEqualTo(String value) {
            addCriterion("TOWN_DIVIDE_FLAG =", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagNotEqualTo(String value) {
            addCriterion("TOWN_DIVIDE_FLAG <>", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagGreaterThan(String value) {
            addCriterion("TOWN_DIVIDE_FLAG >", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagGreaterThanOrEqualTo(String value) {
            addCriterion("TOWN_DIVIDE_FLAG >=", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagLessThan(String value) {
            addCriterion("TOWN_DIVIDE_FLAG <", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagLessThanOrEqualTo(String value) {
            addCriterion("TOWN_DIVIDE_FLAG <=", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagLike(String value) {
            addCriterion("TOWN_DIVIDE_FLAG like", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagNotLike(String value) {
            addCriterion("TOWN_DIVIDE_FLAG not like", value, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagIn(List<String> values) {
            addCriterion("TOWN_DIVIDE_FLAG in", values, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagNotIn(List<String> values) {
            addCriterion("TOWN_DIVIDE_FLAG not in", values, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagBetween(String value1, String value2) {
            addCriterion("TOWN_DIVIDE_FLAG between", value1, value2, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andTownDivideFlagNotBetween(String value1, String value2) {
            addCriterion("TOWN_DIVIDE_FLAG not between", value1, value2, "townDivideFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagIsNull() {
            addCriterion("KOAZA_BANCHI_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagIsNotNull() {
            addCriterion("KOAZA_BANCHI_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagEqualTo(String value) {
            addCriterion("KOAZA_BANCHI_FLAG =", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagNotEqualTo(String value) {
            addCriterion("KOAZA_BANCHI_FLAG <>", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagGreaterThan(String value) {
            addCriterion("KOAZA_BANCHI_FLAG >", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagGreaterThanOrEqualTo(String value) {
            addCriterion("KOAZA_BANCHI_FLAG >=", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagLessThan(String value) {
            addCriterion("KOAZA_BANCHI_FLAG <", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagLessThanOrEqualTo(String value) {
            addCriterion("KOAZA_BANCHI_FLAG <=", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagLike(String value) {
            addCriterion("KOAZA_BANCHI_FLAG like", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagNotLike(String value) {
            addCriterion("KOAZA_BANCHI_FLAG not like", value, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagIn(List<String> values) {
            addCriterion("KOAZA_BANCHI_FLAG in", values, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagNotIn(List<String> values) {
            addCriterion("KOAZA_BANCHI_FLAG not in", values, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagBetween(String value1, String value2) {
            addCriterion("KOAZA_BANCHI_FLAG between", value1, value2, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andKoazaBanchiFlagNotBetween(String value1, String value2) {
            addCriterion("KOAZA_BANCHI_FLAG not between", value1, value2, "koazaBanchiFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagIsNull() {
            addCriterion("TYHOUME_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagIsNotNull() {
            addCriterion("TYHOUME_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagEqualTo(String value) {
            addCriterion("TYHOUME_FLAG =", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagNotEqualTo(String value) {
            addCriterion("TYHOUME_FLAG <>", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagGreaterThan(String value) {
            addCriterion("TYHOUME_FLAG >", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagGreaterThanOrEqualTo(String value) {
            addCriterion("TYHOUME_FLAG >=", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagLessThan(String value) {
            addCriterion("TYHOUME_FLAG <", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagLessThanOrEqualTo(String value) {
            addCriterion("TYHOUME_FLAG <=", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagLike(String value) {
            addCriterion("TYHOUME_FLAG like", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagNotLike(String value) {
            addCriterion("TYHOUME_FLAG not like", value, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagIn(List<String> values) {
            addCriterion("TYHOUME_FLAG in", values, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagNotIn(List<String> values) {
            addCriterion("TYHOUME_FLAG not in", values, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagBetween(String value1, String value2) {
            addCriterion("TYHOUME_FLAG between", value1, value2, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andTyhoumeFlagNotBetween(String value1, String value2) {
            addCriterion("TYHOUME_FLAG not between", value1, value2, "tyhoumeFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagIsNull() {
            addCriterion("HAS_SOME_TOWN_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagIsNotNull() {
            addCriterion("HAS_SOME_TOWN_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagEqualTo(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG =", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagNotEqualTo(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG <>", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagGreaterThan(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG >", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagGreaterThanOrEqualTo(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG >=", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagLessThan(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG <", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagLessThanOrEqualTo(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG <=", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagLike(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG like", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagNotLike(String value) {
            addCriterion("HAS_SOME_TOWN_FLAG not like", value, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagIn(List<String> values) {
            addCriterion("HAS_SOME_TOWN_FLAG in", values, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagNotIn(List<String> values) {
            addCriterion("HAS_SOME_TOWN_FLAG not in", values, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagBetween(String value1, String value2) {
            addCriterion("HAS_SOME_TOWN_FLAG between", value1, value2, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andHasSomeTownFlagNotBetween(String value1, String value2) {
            addCriterion("HAS_SOME_TOWN_FLAG not between", value1, value2, "hasSomeTownFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagIsNull() {
            addCriterion("UPDATE_STATE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagIsNotNull() {
            addCriterion("UPDATE_STATE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagEqualTo(String value) {
            addCriterion("UPDATE_STATE_FLAG =", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagNotEqualTo(String value) {
            addCriterion("UPDATE_STATE_FLAG <>", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagGreaterThan(String value) {
            addCriterion("UPDATE_STATE_FLAG >", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_STATE_FLAG >=", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagLessThan(String value) {
            addCriterion("UPDATE_STATE_FLAG <", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_STATE_FLAG <=", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagLike(String value) {
            addCriterion("UPDATE_STATE_FLAG like", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagNotLike(String value) {
            addCriterion("UPDATE_STATE_FLAG not like", value, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagIn(List<String> values) {
            addCriterion("UPDATE_STATE_FLAG in", values, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagNotIn(List<String> values) {
            addCriterion("UPDATE_STATE_FLAG not in", values, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagBetween(String value1, String value2) {
            addCriterion("UPDATE_STATE_FLAG between", value1, value2, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateStateFlagNotBetween(String value1, String value2) {
            addCriterion("UPDATE_STATE_FLAG not between", value1, value2, "updateStateFlag");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonIsNull() {
            addCriterion("UPDATE_REASON is null");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonIsNotNull() {
            addCriterion("UPDATE_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonEqualTo(String value) {
            addCriterion("UPDATE_REASON =", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonNotEqualTo(String value) {
            addCriterion("UPDATE_REASON <>", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonGreaterThan(String value) {
            addCriterion("UPDATE_REASON >", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_REASON >=", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonLessThan(String value) {
            addCriterion("UPDATE_REASON <", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_REASON <=", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonLike(String value) {
            addCriterion("UPDATE_REASON like", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonNotLike(String value) {
            addCriterion("UPDATE_REASON not like", value, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonIn(List<String> values) {
            addCriterion("UPDATE_REASON in", values, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonNotIn(List<String> values) {
            addCriterion("UPDATE_REASON not in", values, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonBetween(String value1, String value2) {
            addCriterion("UPDATE_REASON between", value1, value2, "updateReason");
            return (Criteria) this;
        }

        public Criteria andUpdateReasonNotBetween(String value1, String value2) {
            addCriterion("UPDATE_REASON not between", value1, value2, "updateReason");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZIP2
     *
     * @mbggenerated do_not_delete_during_merge Sun May 11 11:45:03 JST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}