package jp.co.foo.dto;

import org.supercsv.cellprocessor.Optional;
import org.supercsv.cellprocessor.ParseDate;
import org.supercsv.cellprocessor.ParseInt;
import org.supercsv.cellprocessor.Trim;
import org.supercsv.cellprocessor.constraint.StrMinMax;
import org.supercsv.cellprocessor.constraint.Unique;
import org.supercsv.cellprocessor.ift.CellProcessor;


public class Zip2Dto {
	
    /** 各要素フォーマット定義 */
    public static final CellProcessor[] PROCESSORS = new CellProcessor[] {
    	
    	new StrMinMax(1, 255),    // JIS_CODE                    VARCHAR2(255),
    	new StrMinMax(1, 255), // POSTAL_CODE_OLD             VARCHAR2(255),
        null, // POSTAL_CODE                 VARCHAR2(255),
        null,  // PREFECTURE_KANA             VARCHAR2(255),
        null,  // CITY_KANA                   VARCHAR2(255),
        null,   // TOWN_KANA                   VARCHAR2(255),
        null,  // PREFECTURE_KANJI            VARCHAR2(255),
        null,  // CITY_KANJI                  VARCHAR2(255),
        null,  // TOWN_KANJI                  VARCHAR2(255),
        null,  // TOWN_DIVIDE_FLAG            VARCHAR2(1),
        null,  // KOAZA_BANCHI_FLAG           VARCHAR2(1),
        null,  // TYHOUME_FLAG                VARCHAR2(1),
        null,  // HAS_SOME_TOWN_FLAG          VARCHAR2(1),
        null,   // UPDATE_STATE_FLAG           VARCHAR2(1),
        null// UPDATE_REASON               VARCHAR2(255)    
      };
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.JIS_CODE
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String jisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.POSTAL_CODE_OLD
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String postalCodeOld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.POSTAL_CODE
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.PREFECTURE_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String prefectureKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.CITY_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String cityKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.TOWN_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String townKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.PREFECTURE_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String prefectureKanji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.CITY_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String cityKanji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.TOWN_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String townKanji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.TOWN_DIVIDE_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String townDivideFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.KOAZA_BANCHI_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String koazaBanchiFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.TYHOUME_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String tyhoumeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.HAS_SOME_TOWN_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String hasSomeTownFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.UPDATE_STATE_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String updateStateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZIP2.UPDATE_REASON
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private String updateReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZIP2
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    private static final long serialVersionUID = 1399776303148L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.JIS_CODE
     *
     * @return the value of ZIP2.JIS_CODE
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getJisCode() {
        return jisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.JIS_CODE
     *
     * @param jisCode the value for ZIP2.JIS_CODE
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setJisCode(String jisCode) {
        this.jisCode = jisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.POSTAL_CODE_OLD
     *
     * @return the value of ZIP2.POSTAL_CODE_OLD
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getPostalCodeOld() {
        return postalCodeOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.POSTAL_CODE_OLD
     *
     * @param postalCodeOld the value for ZIP2.POSTAL_CODE_OLD
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setPostalCodeOld(String postalCodeOld) {
        this.postalCodeOld = postalCodeOld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.POSTAL_CODE
     *
     * @return the value of ZIP2.POSTAL_CODE
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.POSTAL_CODE
     *
     * @param postalCode the value for ZIP2.POSTAL_CODE
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.PREFECTURE_KANA
     *
     * @return the value of ZIP2.PREFECTURE_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getPrefectureKana() {
        return prefectureKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.PREFECTURE_KANA
     *
     * @param prefectureKana the value for ZIP2.PREFECTURE_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setPrefectureKana(String prefectureKana) {
        this.prefectureKana = prefectureKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.CITY_KANA
     *
     * @return the value of ZIP2.CITY_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getCityKana() {
        return cityKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.CITY_KANA
     *
     * @param cityKana the value for ZIP2.CITY_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setCityKana(String cityKana) {
        this.cityKana = cityKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.TOWN_KANA
     *
     * @return the value of ZIP2.TOWN_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getTownKana() {
        return townKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.TOWN_KANA
     *
     * @param townKana the value for ZIP2.TOWN_KANA
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setTownKana(String townKana) {
        this.townKana = townKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.PREFECTURE_KANJI
     *
     * @return the value of ZIP2.PREFECTURE_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getPrefectureKanji() {
        return prefectureKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.PREFECTURE_KANJI
     *
     * @param prefectureKanji the value for ZIP2.PREFECTURE_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setPrefectureKanji(String prefectureKanji) {
        this.prefectureKanji = prefectureKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.CITY_KANJI
     *
     * @return the value of ZIP2.CITY_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getCityKanji() {
        return cityKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.CITY_KANJI
     *
     * @param cityKanji the value for ZIP2.CITY_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setCityKanji(String cityKanji) {
        this.cityKanji = cityKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.TOWN_KANJI
     *
     * @return the value of ZIP2.TOWN_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getTownKanji() {
        return townKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.TOWN_KANJI
     *
     * @param townKanji the value for ZIP2.TOWN_KANJI
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setTownKanji(String townKanji) {
        this.townKanji = townKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.TOWN_DIVIDE_FLAG
     *
     * @return the value of ZIP2.TOWN_DIVIDE_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getTownDivideFlag() {
        return townDivideFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.TOWN_DIVIDE_FLAG
     *
     * @param townDivideFlag the value for ZIP2.TOWN_DIVIDE_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setTownDivideFlag(String townDivideFlag) {
        this.townDivideFlag = townDivideFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.KOAZA_BANCHI_FLAG
     *
     * @return the value of ZIP2.KOAZA_BANCHI_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getKoazaBanchiFlag() {
        return koazaBanchiFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.KOAZA_BANCHI_FLAG
     *
     * @param koazaBanchiFlag the value for ZIP2.KOAZA_BANCHI_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setKoazaBanchiFlag(String koazaBanchiFlag) {
        this.koazaBanchiFlag = koazaBanchiFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.TYHOUME_FLAG
     *
     * @return the value of ZIP2.TYHOUME_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getTyhoumeFlag() {
        return tyhoumeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.TYHOUME_FLAG
     *
     * @param tyhoumeFlag the value for ZIP2.TYHOUME_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setTyhoumeFlag(String tyhoumeFlag) {
        this.tyhoumeFlag = tyhoumeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.HAS_SOME_TOWN_FLAG
     *
     * @return the value of ZIP2.HAS_SOME_TOWN_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getHasSomeTownFlag() {
        return hasSomeTownFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.HAS_SOME_TOWN_FLAG
     *
     * @param hasSomeTownFlag the value for ZIP2.HAS_SOME_TOWN_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setHasSomeTownFlag(String hasSomeTownFlag) {
        this.hasSomeTownFlag = hasSomeTownFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.UPDATE_STATE_FLAG
     *
     * @return the value of ZIP2.UPDATE_STATE_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getUpdateStateFlag() {
        return updateStateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.UPDATE_STATE_FLAG
     *
     * @param updateStateFlag the value for ZIP2.UPDATE_STATE_FLAG
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setUpdateStateFlag(String updateStateFlag) {
        this.updateStateFlag = updateStateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZIP2.UPDATE_REASON
     *
     * @return the value of ZIP2.UPDATE_REASON
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public String getUpdateReason() {
        return updateReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZIP2.UPDATE_REASON
     *
     * @param updateReason the value for ZIP2.UPDATE_REASON
     *
     * @mbggenerated Sun May 11 11:45:03 JST 2014
     */
    public void setUpdateReason(String updateReason) {
        this.updateReason = updateReason;
    }
}